# Generated by Django 4.2 on 2026-03-03 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='companydrive',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='companydrive',
            old_name='role',
            new_name='job_role',
        ),
        migrations.AddField(
            model_name='application',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='drive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='package',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Package in LPA', max_digits=10),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='companydrive',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'PLACEMENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('PLACEMENT', 'Placement Officer')], default='STUDENT', max_length=20),
        ),
    ]
