# Generated by Django 4.2 on 2026-03-03 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_application_options_alter_companydrive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='eligibility_remarks',
            field=models.TextField(blank=True, help_text='Remarks about eligibility', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_eligible',
            field=models.BooleanField(default=False, help_text='Marked as eligible by placement officer'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_approved',
            field=models.BooleanField(default=False, help_text='Profile approved by placement officer'),
        ),
    ]
